language: node_js
node_js:
  - '12'
services:
  - mysql
env:
  - NODE_ENV=test
before_install:
  - npm install
  - mysql -e 'CREATE DATABASE IF NOT EXISTS wapd_backend_test default character set
    utf8mb4 collate utf8mb4_unicode_ci;'
  - npm install sequelize-cli -g
  - export CONFIG_USER_NAME=travis
  - export CONFIG_USER_PASS=
before_script:
  - sequelize db:migrate --env test
script:
  - npm run test
deploy:
  provider: heroku
  api_key:
    secure: 905a7c2e-0fd2-484b-ab7c-ce00e27cb2e7
  app:
    master: t-wapd-backend
  on:
    repo: EasonLin0716/wapd-backend
after_success: npm run coverage
